### ISSUE TITLE
Todo:

### ISSUE THREAD

**Issue by xnacly** [xNaCly/betterforum#1]
# General:
- [ ] Add a setup script and create a release (?python?)
- [x] Add example website with dummy values to show the website
    - [ ] update the website to the current code status
- [x] Add REST docs
- [x] ~add the salt and its creation in `config.json` to the setup tutorial~ 
       Added automatic config & salt creation if `config.json` doesn't exist

# Frontend:
- [ ] create a login for mods/admins
- [ ] create a mod/admin dashboard to delete & lockdown posts
- [x] add createThread page/component
- [x] add reply to comments
- [x] add multiple themes (current one is ass)
- [x] add a setting compontent

# Backend:
- [ ] add captchas (hcaptcha) for comment creation
- [ ] allow `PUT`, `DELETE` for mods for `comments`&`threads`
- [x] add hashing of usernames/authorvalues [(bcrypt)](https://www.npmjs.com/package/bcrypt)
- [x] remove asset routes
- [x] add reply to comments
- [ ] ~fix reporting of posts~
